### ISSUE TITLE
PCL Profile 259 not supported?

### ISSUE THREAD

**Issue by IlSocio** [Fody/ToString#18]
Hi,
I tried to install the ToString() component on a PCL targeting profile 259, but I got the error message below...

Could not install package 'ToString.Fody 1.7.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Marco.

**Comment by SimonCropp** [comment]
is this still required? or will netstandard support suffice?
