### ISSUE TITLE
Allow IgnoreDuringToStringAttribute on fields

### ISSUE THREAD

**Issue by nohwnd** [Fody/ToString#19]
Is there a reason not to allow the `IgnoreDuringToStringAttribute` on fields? I am trying to use this plugin with another Fody plugin, [Fielder](https://github.com/Fody/Fielder), that converts fields to properties, and it does not compile because of the `[AttributeUsage(AttributeTargets.Property)]` restriction imposed on the attribute.

If you will allow it, then I will gladly provide a PR.

(Thanks for all the work, just started using the library recently, and I really like it. Tomorrow I am presenting about it to my colleagues :))

**Comment by rjasica** [comment]
At this moment, this plugin uses only properties, so marking fields with this attribute will not work.

**Comment by nohwnd** [comment]
You are just saying the same thing I said. Please see the first sentence: Is there a reason to only work with properties? 

Not allowing it on fields limits the usability of the plugin greatly, and personally I don't see any technical reason not to allow it on fields as well. The only problem I see is that is might be considered a breaking change by some users.

**Comment by SimonCropp** [comment]
happy to accept a PR
