### ISSUE TITLE
IgnoreDuringToString is not working.

### ISSUE THREAD

**Issue by kenichi-kobayashi** [Fody/ToString#320]
IgnoreDuringToString is not working.

I wrote the following code.

    [ToString]
    public abstract class MyBase
    {
        [IgnoreDuringToString]
        public int BaseId { get; set; }
    }

    [ToString]
    public class MyClass1 : Base.MyBase
    {
        public string Name { get; set; }
    }

    [ToString]
    public class MyClass2 : Base.MyBase
    {
        public string Name { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var myClass1 = new MyClass1();
            myClass1.BaseId = 9999;
            Debug.WriteLine(myClass1.ToString());

            var myClass2 = new MyClass2();
            myClass2.BaseId = 6666;
            Debug.WriteLine(myClass2.ToString());
        }
    }

![NG](https://user-images.githubusercontent.com/47070699/113424769-acd31d80-940b-11eb-923d-b6611532010d.png)

When I execute ToString on MyClass2, "BaseId" that sets "IgnoreDuringToString" is displayed.

[FodyToStringTest.zip](https://github.com/Fody/ToString/files/6249988/FodyToStringTest.zip)

**Comment by SimonCropp** [comment]
please re read the issue template and fill out all the information

**Comment by kenichi-kobayashi** [comment]
Sorry for the lack of information.
Added necessary information.
Is there any other missing information?

My first language is Japanese.
If I don't understand your intentions correctly, I would appreciate it if you could point it out.

#### Preamble

Fody : 6.0.0
ToString.Fody : 1.11.0
Project F/W Version : .NET 5.0

#### Describe the issue

IgnoreDuringToString is not working.

I wrote the following code.

#### Minimal Repro

[ToString]
public abstract class MyBase
{
    [IgnoreDuringToString]
    public int BaseId { get; set; }
}

[ToString]
public class MyClass1 : Base.MyBase
{
    public string Name { get; set; }
}

[ToString]
public class MyClass2 : Base.MyBase
{
    public string Name { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        var myClass1 = new MyClass1();
        myClass1.BaseId = 9999;
        Debug.WriteLine(myClass1.ToString());

        var myClass2 = new MyClass2();
        myClass2.BaseId = 6666;
        Debug.WriteLine(myClass2.ToString());
    }
}

[FodyToStringTest.zip](https://github.com/Fody/ToString/files/6255886/FodyToStringTest.zip)

**Comment by SimonCropp** [comment]
so just checking, are you a patron on opencollective ? https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#licensingpatron-faq

**Comment by kenichi-kobayashi** [comment]
Sorry, I am not patron.
Therefore, I reject this issue.
