### ISSUE TITLE
Add inheritable ToStringAttribute

### ISSUE THREAD

**Issue by elmondir** [Fody/ToString#63]
What about Adding An inheritable ToStringAttribute

I Finished That by Overriding the default ToStringAttribute By that
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = true)]
    public sealed class ToStringAttribute : Attribute
    {
    }
 it work fine
but what about making  an option for that.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
