### ISSUE TITLE
Add Option To Ignore PropertyName

### ISSUE THREAD

**Issue by elmondir** [Fody/ToString#64]
Hi 
Can you Add an option to ignore propertyName and show values only 
and an option to ignore null propertyValues

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
